include ../../.Makefile.arch
include ../../.Makefile.REST

CLASSES = TRestGeant4AnalysisProcess TRestSignalAnalysisProcess TRestFindG4BlobAnalysisProcess TRestTrackAnalysisProcess

include ../../.Makefile.Class
