#------------------------------------------------------------------------------
#                                                                      
#                                                                      
#   RESTSoft : Software for Rare Event Searches with TPCs
#   Makefile to create the RESTsofts libraries
#                                                                      
#      submodule: RESTMETADATA
#    
#   Created  :  Oct 2015                                             
#   Auth: J. Galan
#
#------------------------------------------------------------------------------
# generic info on makefiles:
# http://www.gnu.org/software/make/manual/make.html
#------------------------------------------------------------------------------

include ../.Makefile.arch
include ../.Makefile.REST

# Name of RESTsoft module(s) to compile
MODULE = RestProcesses

DIRECTORIES = general raw

LIBS += -lRestEvents
include ../.Makefile.Lib
