include ../../.Makefile.arch
include ../../.Makefile.REST

CLASSES = TRestElectronDiffusionProcess TRestHitsToSignalProcess TRestHitsToTrackProcess TRestFastHitsToTrackProcess TRestSignalToHitsProcess TRestTrackReductionProcess TRestTrackPathMinimizationProcess TRestAvalancheProcess TRestTrackLinearizationProcess

include ../../.Makefile.Class
