- label: "PR submitted by:"
  message: "$payload.pull_request.user.login"
  color: "blue"
- label: "PR Size"
  message: "Large"
  color: "red"
  when: "$additions > 200"
- label: "PR Size"
  message: "Medium"
  color: "orange"
  when: "$additions > 100"
- label: "PR Size"
  message: "Ok"
  color: "green"
  when: "$additions < 100"
- imageUrl: "https://gitlab.cern.ch/rest-for-physics/framework/badges/$branchName/pipeline.svg"
  url: "https://gitlab.cern.ch/rest-for-physics/framework/-/commits/$branchName"
