- label: "PR submitted by:"
  message: "$payload.pull_request.user.login"
  color: "blue"
- label: "PR Size"
  message: "Large: $additions"
  color: "red"
  when: "$additions > 200"
- label: "PR Size"
  message: "Medium: $additions"
  color: "orange"
  when: "$additions > 99 && $additions < 201"
- label: "PR Size"
  message: "Ok: $additions"
  color: "green"
  when: "$additions < 100"
- imageUrl: "https://github.com/rest-for-physics/framework/actions/workflows/validation.yml/badge.svg?branch=$branchName"
  url: "https://github.com/rest-for-physics/framework/commits/$branchName"
