/********************************************************************
* dict/TRestRunMerger.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestRunMerger.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestRunMerger();
extern void G__cpp_setup_inheritanceTRestRunMerger();
extern void G__cpp_setup_typetableTRestRunMerger();
extern void G__cpp_setup_memvarTRestRunMerger();
extern void G__cpp_setup_globalTRestRunMerger();
extern void G__cpp_setup_memfuncTRestRunMerger();
extern void G__cpp_setup_funcTRestRunMerger();
extern void G__set_cpp_environmentTRestRunMerger();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestRunMerger.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestRunMergerLN_TClass;
extern G__linked_taginfo G__TRestRunMergerLN_TBuffer;
extern G__linked_taginfo G__TRestRunMergerLN_TMemberInspector;
extern G__linked_taginfo G__TRestRunMergerLN_TObject;
extern G__linked_taginfo G__TRestRunMergerLN_TString;
extern G__linked_taginfo G__TRestRunMergerLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestRunMergerLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestRunMergerLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestRunMergerLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestRunMergerLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TRestRunMergerLN_TFile;
extern G__linked_taginfo G__TRestRunMergerLN_TFileMerger;
extern G__linked_taginfo G__TRestRunMergerLN_TRestRunMerger;
extern G__linked_taginfo G__TRestRunMergerLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TRestRunMergerLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
