/********************************************************************
* dict/TRestBrowser.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestBrowser.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestBrowser();
extern void G__cpp_setup_inheritanceTRestBrowser();
extern void G__cpp_setup_typetableTRestBrowser();
extern void G__cpp_setup_memvarTRestBrowser();
extern void G__cpp_setup_globalTRestBrowser();
extern void G__cpp_setup_memfuncTRestBrowser();
extern void G__cpp_setup_funcTRestBrowser();
extern void G__set_cpp_environmentTRestBrowser();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestBrowser.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestBrowserLN_TClass;
extern G__linked_taginfo G__TRestBrowserLN_TBuffer;
extern G__linked_taginfo G__TRestBrowserLN_TMemberInspector;
extern G__linked_taginfo G__TRestBrowserLN_TString;
extern G__linked_taginfo G__TRestBrowserLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestBrowserLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestBrowserLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestBrowserLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestBrowserLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__TRestBrowserLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__TRestBrowserLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestBrowserLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TRestBrowserLN_TGTextButton;
extern G__linked_taginfo G__TRestBrowserLN_TGVerticalFrame;
extern G__linked_taginfo G__TRestBrowserLN_TGMainFrame;
extern G__linked_taginfo G__TRestBrowserLN_TGPictureButton;
extern G__linked_taginfo G__TRestBrowserLN_TGNumberEntry;
extern G__linked_taginfo G__TRestBrowserLN_TRestBrowser;

/* STUB derived class for protected member access */
