/********************************************************************
* dict/TRestRun.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestRun.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestRun();
extern void G__cpp_setup_inheritanceTRestRun();
extern void G__cpp_setup_typetableTRestRun();
extern void G__cpp_setup_memvarTRestRun();
extern void G__cpp_setup_globalTRestRun();
extern void G__cpp_setup_memfuncTRestRun();
extern void G__cpp_setup_funcTRestRun();
extern void G__set_cpp_environmentTRestRun();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestRun.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestRunLN_TClass;
extern G__linked_taginfo G__TRestRunLN_TBuffer;
extern G__linked_taginfo G__TRestRunLN_TMemberInspector;
extern G__linked_taginfo G__TRestRunLN_TObject;
extern G__linked_taginfo G__TRestRunLN_TNamed;
extern G__linked_taginfo G__TRestRunLN_TString;
extern G__linked_taginfo G__TRestRunLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestRunLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestRunLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestRunLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestRunLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TRestRunLN_TFile;
extern G__linked_taginfo G__TRestRunLN_TTree;
extern G__linked_taginfo G__TRestRunLN_maplElongcOintcOlesslElonggRcOallocatorlEpairlEconstsPlongcOintgRsPgRsPgR;
extern G__linked_taginfo G__TRestRunLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TRestRunLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR;
extern G__linked_taginfo G__TRestRunLN_TGeoManager;
extern G__linked_taginfo G__TRestRunLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR;
extern G__linked_taginfo G__TRestRunLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestRunLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TRestRunLN_TRestEvent;
extern G__linked_taginfo G__TRestRunLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TRestRunLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TRestRunLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TRestRunLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TRestRunLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TRestRunLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TRestRunLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TRestRunLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TRestRunLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TRestRunLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestRunLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TRestRunLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TRestRunLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TRestRunLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TRestRunLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestRunLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TRestRunLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TRestRunLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TRestRunLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TRestRunLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TRestRunLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TRestRunLN_TRestMetadata;
extern G__linked_taginfo G__TRestRunLN_TRestEventProcess;
extern G__linked_taginfo G__TRestRunLN_TRestRun;
extern G__linked_taginfo G__TRestRunLN_vectorlETRestMetadatamUcOallocatorlETRestMetadatamUgRsPgR;
extern G__linked_taginfo G__TRestRunLN_reverse_iteratorlEvectorlETRestMetadatamUcOallocatorlETRestMetadatamUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
