/********************************************************************
* dict/TRestMetadata.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestMetadata.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestMetadata();
extern void G__cpp_setup_inheritanceTRestMetadata();
extern void G__cpp_setup_typetableTRestMetadata();
extern void G__cpp_setup_memvarTRestMetadata();
extern void G__cpp_setup_globalTRestMetadata();
extern void G__cpp_setup_memfuncTRestMetadata();
extern void G__cpp_setup_funcTRestMetadata();
extern void G__set_cpp_environmentTRestMetadata();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestMetadata.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestMetadataLN_TClass;
extern G__linked_taginfo G__TRestMetadataLN_TBuffer;
extern G__linked_taginfo G__TRestMetadataLN_TMemberInspector;
extern G__linked_taginfo G__TRestMetadataLN_TObject;
extern G__linked_taginfo G__TRestMetadataLN_TNamed;
extern G__linked_taginfo G__TRestMetadataLN_TString;
extern G__linked_taginfo G__TRestMetadataLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__TRestMetadataLN_string;
extern G__linked_taginfo G__TRestMetadataLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestMetadataLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestMetadataLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestMetadataLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestMetadataLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TRestMetadataLN_TVector2;
extern G__linked_taginfo G__TRestMetadataLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TRestMetadataLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TRestMetadataLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TRestMetadataLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TRestMetadataLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TRestMetadataLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TRestMetadataLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TRestMetadataLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TRestMetadataLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TRestMetadataLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestMetadataLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TRestMetadataLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TRestMetadataLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TRestMetadataLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TRestMetadataLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestMetadataLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TRestMetadataLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TRestMetadataLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TRestMetadataLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TRestMetadataLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TRestMetadataLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TRestMetadataLN_TVector3;
extern G__linked_taginfo G__TRestMetadataLN_REST_Verbose_Level;
extern G__linked_taginfo G__TRestMetadataLN_TRestMetadata;

/* STUB derived class for protected member access */
