/********************************************************************
* dict/TRestEvent.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestEvent.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestEvent();
extern void G__cpp_setup_inheritanceTRestEvent();
extern void G__cpp_setup_typetableTRestEvent();
extern void G__cpp_setup_memvarTRestEvent();
extern void G__cpp_setup_globalTRestEvent();
extern void G__cpp_setup_memfuncTRestEvent();
extern void G__cpp_setup_funcTRestEvent();
extern void G__set_cpp_environmentTRestEvent();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestEventLN_TClass;
extern G__linked_taginfo G__TRestEventLN_TBuffer;
extern G__linked_taginfo G__TRestEventLN_TMemberInspector;
extern G__linked_taginfo G__TRestEventLN_TObject;
extern G__linked_taginfo G__TRestEventLN_TString;
extern G__linked_taginfo G__TRestEventLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestEventLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestEventLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestEventLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestEventLN_TTimeStamp;
extern G__linked_taginfo G__TRestEventLN_TRestEvent;

/* STUB derived class for protected member access */
