include ../../.Makefile.arch
include ../../.Makefile.REST

CLASSES = TRestReadout TRestReadoutPlane TRestReadoutModule TRestReadoutChannel TRestReadoutPixel TRestReadoutMapping

include ../../.Makefile.Class
