include ../../.Makefile.arch
include ../../.Makefile.REST

CLASSES = TRestReadout TRestReadoutModule TRestReadoutChannel TRestReadoutPixel TRestReadoutMapping TRestDecoding

include ../../.Makefile.Class
