include ../../.Makefile.arch
include ../../.Makefile.REST

CLASSES = TRestReadout TRestReadoutPlane TRestReadoutModule TRestReadoutChannel TRestReadoutPixel TRestReadoutMapping TRestDecoding

include ../../.Makefile.Class
