#ifndef REST_Version
#define REST_Version
/* Version information automatically generated by installer. */ /*
                                                                 * These macros can be used in the following
                                                                 * way:
                                                                 *
                                                                 * #if REST_VERSION_CODE >=
                                                                 * REST_VERSION(2,23,4) #include <newheader.h>
                                                                 * #else
                                                                 *     #include <oldheader.h>
                                                                 * #endif
                                                                 *
                                                                 */
#define REST_RELEASE "2.3.13"
#define REST_RELEASE_DATE "Thu 29 Sep"
#define REST_RELEASE_TIME "2022 09:59:23 PM CEST"
#define REST_GIT_COMMIT "46855729"
#define REST_VERSION_CODE 131853
#define REST_VERSION(a, b, c) (((a) << 16) + ((b) << 8) + (c))
#define REST_SCHEMA_EVOLUTION "ON"
#endif
