#ifndef REST_Version
#define REST_Version
/* Version information automatically generated by installer. */ /*
                                                                 * These macros can be used in the following
                                                                 * way:
                                                                 *
                                                                 * #if REST_VERSION_CODE >=
                                                                 * REST_VERSION(2,23,4) #include <newheader.h>
                                                                 * #else
                                                                 *     #include <oldheader.h>
                                                                 * #endif
                                                                 *
                                                                 */
#define REST_RELEASE "2.3.15"
#define REST_RELEASE_DATE "Fri 30 Dec"
#define REST_RELEASE_TIME "2022 08:49:05 AM CET"
#define REST_RELEASE_NAME "David R. Nygren"
#define REST_GIT_COMMIT "ed155a15"
#define REST_VERSION_CODE 131855
#define REST_VERSION(a, b, c) (((a) << 16) + ((b) << 8) + (c))
#define REST_SCHEMA_EVOLUTION "ON"
#endif
