#ifndef REST_Version
#define REST_Version
/* Version information automatically generated by installer. */ /*
                                                                 * These macros can be used in the following
                                                                 * way:
                                                                 *
                                                                 * #if REST_VERSION_CODE >=
                                                                 * REST_VERSION(2,23,4) #include <newheader.h>
                                                                 * #else
                                                                 *     #include <oldheader.h>
                                                                 * #endif
                                                                 *
                                                                 */
#define REST_RELEASE "2.3.10"
#define REST_RELEASE_DATE "Sat 29 Jan"
#define REST_RELEASE_TIME "2022 11:51:37 AM CET"
#define REST_GIT_COMMIT "56030bd8"
#define REST_VERSION_CODE 131850
#define REST_VERSION(a, b, c) (((a) << 16) + ((b) << 8) + (c))
#define REST_SCHEMA_EVOLUTION "ON"
#endif
