name: "Check if a particular label is present in a PR"
inputs:
  label:
    description: "Label to check"
    required: true
outputs:
  label-is-present:
    description: "Return true or false if the label is present"
    value: ${{ steps.label-check.outputs.exist }}

runs:
  using: 'composite'
  steps:
  - name: Label is present
    id: label-check
    run: |
      prlabel=${{ github.event.pull_request.labels.*.name }}
      echo "Label " ${{ github.event.pull_request.labels.*.name }}
      echo "PRlabel ${prlabel[*]}"
      if [[ " ${prlabel[*]} " =~ ${{ inputs.label }} ]]; then
        echo "Label " ${{ inputs.label }}  "is present "
        echo "exist=true" >> $GITHUB_OUTPUT
      else
        echo "Label " ${{ inputs.label }}  "is missing "
        echo "exist=false" >> $GITHUB_OUTPUT
      fi
    shell: bash
