/********************************************************************
* dict/TRestG4Metadata.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestG4Metadata.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestG4Metadata();
extern void G__cpp_setup_inheritanceTRestG4Metadata();
extern void G__cpp_setup_typetableTRestG4Metadata();
extern void G__cpp_setup_memvarTRestG4Metadata();
extern void G__cpp_setup_globalTRestG4Metadata();
extern void G__cpp_setup_memfuncTRestG4Metadata();
extern void G__cpp_setup_funcTRestG4Metadata();
extern void G__set_cpp_environmentTRestG4Metadata();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestG4Metadata.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestG4MetadataLN_TClass;
extern G__linked_taginfo G__TRestG4MetadataLN_TBuffer;
extern G__linked_taginfo G__TRestG4MetadataLN_TMemberInspector;
extern G__linked_taginfo G__TRestG4MetadataLN_TObject;
extern G__linked_taginfo G__TRestG4MetadataLN_TNamed;
extern G__linked_taginfo G__TRestG4MetadataLN_TString;
extern G__linked_taginfo G__TRestG4MetadataLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TRestG4MetadataLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestG4MetadataLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestG4MetadataLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestG4MetadataLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestG4MetadataLN_TVector2;
extern G__linked_taginfo G__TRestG4MetadataLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TRestG4MetadataLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TRestG4MetadataLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TRestG4MetadataLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TRestG4MetadataLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TRestG4MetadataLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TRestG4MetadataLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TRestG4MetadataLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TRestG4MetadataLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TRestG4MetadataLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestG4MetadataLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TRestG4MetadataLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TRestG4MetadataLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TRestG4MetadataLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TRestG4MetadataLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestG4MetadataLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TRestG4MetadataLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TRestG4MetadataLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TRestG4MetadataLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TRestG4MetadataLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TRestG4MetadataLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TRestG4MetadataLN_TVector3;
extern G__linked_taginfo G__TRestG4MetadataLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TRestG4MetadataLN_TRestMetadata;
extern G__linked_taginfo G__TRestG4MetadataLN_TRestParticleSource;
extern G__linked_taginfo G__TRestG4MetadataLN_vectorlETRestParticlecOallocatorlETRestParticlegRsPgR;
extern G__linked_taginfo G__TRestG4MetadataLN_reverse_iteratorlEvectorlETRestParticlecOallocatorlETRestParticlegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestG4MetadataLN_TRestG4PrimaryGenerator;
extern G__linked_taginfo G__TRestG4MetadataLN_vectorlETRestParticleSourcecOallocatorlETRestParticleSourcegRsPgR;
extern G__linked_taginfo G__TRestG4MetadataLN_reverse_iteratorlEvectorlETRestParticleSourcecOallocatorlETRestParticleSourcegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestG4MetadataLN_vectorlETRestParticleCollectioncOallocatorlETRestParticleCollectiongRsPgR;
extern G__linked_taginfo G__TRestG4MetadataLN_reverse_iteratorlEvectorlETRestParticleCollectioncOallocatorlETRestParticleCollectiongRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestG4MetadataLN_TRestBiasingVolume;
extern G__linked_taginfo G__TRestG4MetadataLN_TRestG4Metadata;
extern G__linked_taginfo G__TRestG4MetadataLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TRestG4MetadataLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestG4MetadataLN_vectorlETRestBiasingVolumecOallocatorlETRestBiasingVolumegRsPgR;
extern G__linked_taginfo G__TRestG4MetadataLN_reverse_iteratorlEvectorlETRestBiasingVolumecOallocatorlETRestBiasingVolumegRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
