/********************************************************************
* dict/TRestGas.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestGas.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestGas();
extern void G__cpp_setup_inheritanceTRestGas();
extern void G__cpp_setup_typetableTRestGas();
extern void G__cpp_setup_memvarTRestGas();
extern void G__cpp_setup_globalTRestGas();
extern void G__cpp_setup_memfuncTRestGas();
extern void G__cpp_setup_funcTRestGas();
extern void G__set_cpp_environmentTRestGas();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestGas.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestGasLN_TClass;
extern G__linked_taginfo G__TRestGasLN_TBuffer;
extern G__linked_taginfo G__TRestGasLN_TMemberInspector;
extern G__linked_taginfo G__TRestGasLN_TObject;
extern G__linked_taginfo G__TRestGasLN_TNamed;
extern G__linked_taginfo G__TRestGasLN_TString;
extern G__linked_taginfo G__TRestGasLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TRestGasLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TRestGasLN_string;
extern G__linked_taginfo G__TRestGasLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestGasLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestGasLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestGasLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestGasLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TRestGasLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TRestGasLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestGasLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TRestGasLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TRestGasLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__TRestGasLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__TRestGasLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestGasLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TRestGasLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TRestGasLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TRestGasLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TRestGasLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TRestGasLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TRestGasLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TRestGasLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestGasLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TRestGasLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TRestGasLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TRestGasLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TRestGasLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestGasLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TRestGasLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TRestGasLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TRestGasLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TRestGasLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TRestGasLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TRestGasLN_TRestMetadata;
extern G__linked_taginfo G__TRestGasLN_TRestGas;

/* STUB derived class for protected member access */
