/********************************************************************
* dict/TRestReadout.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestReadout.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestReadout();
extern void G__cpp_setup_inheritanceTRestReadout();
extern void G__cpp_setup_typetableTRestReadout();
extern void G__cpp_setup_memvarTRestReadout();
extern void G__cpp_setup_globalTRestReadout();
extern void G__cpp_setup_memfuncTRestReadout();
extern void G__cpp_setup_funcTRestReadout();
extern void G__set_cpp_environmentTRestReadout();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestReadout.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestReadoutLN_TClass;
extern G__linked_taginfo G__TRestReadoutLN_TBuffer;
extern G__linked_taginfo G__TRestReadoutLN_TMemberInspector;
extern G__linked_taginfo G__TRestReadoutLN_TObject;
extern G__linked_taginfo G__TRestReadoutLN_TNamed;
extern G__linked_taginfo G__TRestReadoutLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestReadoutLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestReadoutLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestReadoutLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestReadoutLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TRestReadoutLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TRestReadoutLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TRestReadoutLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TRestReadoutLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TRestReadoutLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TRestReadoutLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TRestReadoutLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TRestReadoutLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TRestReadoutLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TRestReadoutLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestReadoutLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TRestReadoutLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TRestReadoutLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TRestReadoutLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TRestReadoutLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestReadoutLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TRestReadoutLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TRestReadoutLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TRestReadoutLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TRestReadoutLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TRestReadoutLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TRestReadoutLN_TRestMetadata;
extern G__linked_taginfo G__TRestReadoutLN_vectorlETRestReadoutPixelcOallocatorlETRestReadoutPixelgRsPgR;
extern G__linked_taginfo G__TRestReadoutLN_reverse_iteratorlEvectorlETRestReadoutPixelcOallocatorlETRestReadoutPixelgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestReadoutLN_TRestReadoutModule;
extern G__linked_taginfo G__TRestReadoutLN_vectorlETRestReadoutChannelcOallocatorlETRestReadoutChannelgRsPgR;
extern G__linked_taginfo G__TRestReadoutLN_reverse_iteratorlEvectorlETRestReadoutChannelcOallocatorlETRestReadoutChannelgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestReadoutLN_TRestReadout;
extern G__linked_taginfo G__TRestReadoutLN_vectorlETRestReadoutModulecOallocatorlETRestReadoutModulegRsPgR;
extern G__linked_taginfo G__TRestReadoutLN_reverse_iteratorlEvectorlETRestReadoutModulecOallocatorlETRestReadoutModulegRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
