/********************************************************************
* dict/TRestReadoutModule.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestReadoutModule.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestReadoutModule();
extern void G__cpp_setup_inheritanceTRestReadoutModule();
extern void G__cpp_setup_typetableTRestReadoutModule();
extern void G__cpp_setup_memvarTRestReadoutModule();
extern void G__cpp_setup_globalTRestReadoutModule();
extern void G__cpp_setup_memfuncTRestReadoutModule();
extern void G__cpp_setup_funcTRestReadoutModule();
extern void G__set_cpp_environmentTRestReadoutModule();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestReadoutModule.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestReadoutModuleLN_TClass;
extern G__linked_taginfo G__TRestReadoutModuleLN_TBuffer;
extern G__linked_taginfo G__TRestReadoutModuleLN_TMemberInspector;
extern G__linked_taginfo G__TRestReadoutModuleLN_TObject;
extern G__linked_taginfo G__TRestReadoutModuleLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestReadoutModuleLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestReadoutModuleLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestReadoutModuleLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestReadoutModuleLN_TVector2;
extern G__linked_taginfo G__TRestReadoutModuleLN_TRestReadoutChannel;
extern G__linked_taginfo G__TRestReadoutModuleLN_vectorlETRestReadoutPixelcOallocatorlETRestReadoutPixelgRsPgR;
extern G__linked_taginfo G__TRestReadoutModuleLN_reverse_iteratorlEvectorlETRestReadoutPixelcOallocatorlETRestReadoutPixelgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestReadoutModuleLN_TRestReadoutModule;
extern G__linked_taginfo G__TRestReadoutModuleLN_vectorlETRestReadoutChannelcOallocatorlETRestReadoutChannelgRsPgR;
extern G__linked_taginfo G__TRestReadoutModuleLN_reverse_iteratorlEvectorlETRestReadoutChannelcOallocatorlETRestReadoutChannelgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
