/********************************************************************
* dict/TRestReadoutChannel.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestReadoutChannel.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestReadoutChannel();
extern void G__cpp_setup_inheritanceTRestReadoutChannel();
extern void G__cpp_setup_typetableTRestReadoutChannel();
extern void G__cpp_setup_memvarTRestReadoutChannel();
extern void G__cpp_setup_globalTRestReadoutChannel();
extern void G__cpp_setup_memfuncTRestReadoutChannel();
extern void G__cpp_setup_funcTRestReadoutChannel();
extern void G__set_cpp_environmentTRestReadoutChannel();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestReadoutChannel.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestReadoutChannelLN_TClass;
extern G__linked_taginfo G__TRestReadoutChannelLN_TBuffer;
extern G__linked_taginfo G__TRestReadoutChannelLN_TMemberInspector;
extern G__linked_taginfo G__TRestReadoutChannelLN_TObject;
extern G__linked_taginfo G__TRestReadoutChannelLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestReadoutChannelLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestReadoutChannelLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestReadoutChannelLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestReadoutChannelLN_TRestReadoutPixel;
extern G__linked_taginfo G__TRestReadoutChannelLN_TRestReadoutChannel;
extern G__linked_taginfo G__TRestReadoutChannelLN_vectorlETRestReadoutPixelcOallocatorlETRestReadoutPixelgRsPgR;
extern G__linked_taginfo G__TRestReadoutChannelLN_reverse_iteratorlEvectorlETRestReadoutPixelcOallocatorlETRestReadoutPixelgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
