/********************************************************************
* dict/TRestReadoutPixel.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestReadoutPixel.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestReadoutPixel();
extern void G__cpp_setup_inheritanceTRestReadoutPixel();
extern void G__cpp_setup_typetableTRestReadoutPixel();
extern void G__cpp_setup_memvarTRestReadoutPixel();
extern void G__cpp_setup_globalTRestReadoutPixel();
extern void G__cpp_setup_memfuncTRestReadoutPixel();
extern void G__cpp_setup_funcTRestReadoutPixel();
extern void G__set_cpp_environmentTRestReadoutPixel();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestReadoutPixel.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestReadoutPixelLN_TClass;
extern G__linked_taginfo G__TRestReadoutPixelLN_TBuffer;
extern G__linked_taginfo G__TRestReadoutPixelLN_TMemberInspector;
extern G__linked_taginfo G__TRestReadoutPixelLN_TObject;
extern G__linked_taginfo G__TRestReadoutPixelLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestReadoutPixelLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestReadoutPixelLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestReadoutPixelLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestReadoutPixelLN_TVector2;
extern G__linked_taginfo G__TRestReadoutPixelLN_TRestReadoutPixel;

/* STUB derived class for protected member access */
