include ../../.Makefile.arch
include ../../.Makefile.REST

CLASSES = TRestEveEventViewer TRestHitsEventViewer TRestSignalEventViewer TRestReadoutEventViewer TRestTrackEventViewer

include ../../.Makefile.Class
