name: "Validation Action"
description: "Runs the validation workflow in the proper branch"
inputs:
  branch:
    description: "Branch to checkout"
    required: true
  repository:
    description: "Repository"
    required: true
  path:
    description: "Path"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        path: submodule
    - name: Checkout repository branch
      run: |
          cd submodule
          var=$(git ls-remote --heads origin ${{ inputs.branch }})
          if [[ -z $var ]]; then
            echo "Branch "${{ inputs.branch }}" not found in " ${{ inputs.repository }}
            echo "exist=false" >> $GITHUB_OUTPUT
          else
            echo "Branch "${{ inputs.branch }}" found in " ${{ inputs.repository }}
            git fetch
            git checkout ${{ inputs.branch }}
            git pull
          fi
          ls -lrth .github/workflows/validation.yml
      shell: bash
      - name: Debug
      run: |
          ls -lrth submodule
          ls -lrth .github/workflows/validation.yml
      shell: bash
    - name: Validate library
      uses: ./submodule/.github/workflows/validation.yml
