include ../../.Makefile.arch
include ../../.Makefile.REST

CLASSES = TRestSignalDeconvolutionProcess TRestAddSignalNoiseProcess TRestSignalGaussianConvolutionProcess TRestSignalShapingProcess TRestSignalToRawSignalProcess

include ../../.Makefile.Class
