#------------------------------------------------------------------------------
#                                                                      
#                                                                      
#   RESTSoft : Software for Rare Event Searches with TPCs
#   Makefile to create the RESTsofts libraries
#                                                                      
#      submodule: RESTVIEWERS
#    
#   Created  :  Nov 2015                                             
#   Auth: JuanAn Garcia
#
#------------------------------------------------------------------------------
# generic info on makefiles:
# http://www.gnu.org/software/make/manual/make.html
#------------------------------------------------------------------------------

include ../.Makefile.arch
include ../.Makefile.REST

# Name of RESTsoft module(s) to compile
MODULE = RestViewers

DIRECTORIES = general geant4

LIBS += -lRestEvents
include ../.Makefile.Lib
