/********************************************************************
* dict/TRestParticleSource.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestParticleSource.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestParticleSource();
extern void G__cpp_setup_inheritanceTRestParticleSource();
extern void G__cpp_setup_typetableTRestParticleSource();
extern void G__cpp_setup_memvarTRestParticleSource();
extern void G__cpp_setup_globalTRestParticleSource();
extern void G__cpp_setup_memfuncTRestParticleSource();
extern void G__cpp_setup_funcTRestParticleSource();
extern void G__set_cpp_environmentTRestParticleSource();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestParticleSource.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestParticleSourceLN_TClass;
extern G__linked_taginfo G__TRestParticleSourceLN_TBuffer;
extern G__linked_taginfo G__TRestParticleSourceLN_TMemberInspector;
extern G__linked_taginfo G__TRestParticleSourceLN_TObject;
extern G__linked_taginfo G__TRestParticleSourceLN_TString;
extern G__linked_taginfo G__TRestParticleSourceLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestParticleSourceLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestParticleSourceLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestParticleSourceLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestParticleSourceLN_TVector2;
extern G__linked_taginfo G__TRestParticleSourceLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TRestParticleSourceLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TRestParticleSourceLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TRestParticleSourceLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TRestParticleSourceLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TRestParticleSourceLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TRestParticleSourceLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TRestParticleSourceLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TRestParticleSourceLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TRestParticleSourceLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestParticleSourceLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TRestParticleSourceLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TRestParticleSourceLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TRestParticleSourceLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TRestParticleSourceLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestParticleSourceLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TRestParticleSourceLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TRestParticleSourceLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TRestParticleSourceLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TRestParticleSourceLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TRestParticleSourceLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TRestParticleSourceLN_TVector3;
extern G__linked_taginfo G__TRestParticleSourceLN_TRestParticle;
extern G__linked_taginfo G__TRestParticleSourceLN_TRestParticleSource;

/* STUB derived class for protected member access */
