/********************************************************************
* dict/TRestBiasingVolume.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestBiasingVolume.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestBiasingVolume();
extern void G__cpp_setup_inheritanceTRestBiasingVolume();
extern void G__cpp_setup_typetableTRestBiasingVolume();
extern void G__cpp_setup_memvarTRestBiasingVolume();
extern void G__cpp_setup_globalTRestBiasingVolume();
extern void G__cpp_setup_memfuncTRestBiasingVolume();
extern void G__cpp_setup_funcTRestBiasingVolume();
extern void G__set_cpp_environmentTRestBiasingVolume();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestBiasingVolume.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestBiasingVolumeLN_TClass;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TBuffer;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TMemberInspector;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TObject;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TString;
extern G__linked_taginfo G__TRestBiasingVolumeLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TVector2;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TVector3;
extern G__linked_taginfo G__TRestBiasingVolumeLN_TRestBiasingVolume;

/* STUB derived class for protected member access */
