/********************************************************************
* dict/TRestParticleCollection.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestParticleCollection.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestParticleCollection();
extern void G__cpp_setup_inheritanceTRestParticleCollection();
extern void G__cpp_setup_typetableTRestParticleCollection();
extern void G__cpp_setup_memvarTRestParticleCollection();
extern void G__cpp_setup_globalTRestParticleCollection();
extern void G__cpp_setup_memfuncTRestParticleCollection();
extern void G__cpp_setup_funcTRestParticleCollection();
extern void G__set_cpp_environmentTRestParticleCollection();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestParticleCollection.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestParticleCollectionLN_TClass;
extern G__linked_taginfo G__TRestParticleCollectionLN_TBuffer;
extern G__linked_taginfo G__TRestParticleCollectionLN_TMemberInspector;
extern G__linked_taginfo G__TRestParticleCollectionLN_TObject;
extern G__linked_taginfo G__TRestParticleCollectionLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TRestParticleCollectionLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TRestParticleCollectionLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_TRestParticle;
extern G__linked_taginfo G__TRestParticleCollectionLN_TRestParticleCollection;
extern G__linked_taginfo G__TRestParticleCollectionLN_vectorlETRestParticlecOallocatorlETRestParticlegRsPgR;
extern G__linked_taginfo G__TRestParticleCollectionLN_reverse_iteratorlEvectorlETRestParticlecOallocatorlETRestParticlegRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
