/********************************************************************
* dict/TRestG4PrimaryGenerator.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestG4PrimaryGenerator.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestG4PrimaryGenerator();
extern void G__cpp_setup_inheritanceTRestG4PrimaryGenerator();
extern void G__cpp_setup_typetableTRestG4PrimaryGenerator();
extern void G__cpp_setup_memvarTRestG4PrimaryGenerator();
extern void G__cpp_setup_globalTRestG4PrimaryGenerator();
extern void G__cpp_setup_memfuncTRestG4PrimaryGenerator();
extern void G__cpp_setup_funcTRestG4PrimaryGenerator();
extern void G__set_cpp_environmentTRestG4PrimaryGenerator();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestG4PrimaryGenerator.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TClass;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TBuffer;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TMemberInspector;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TObject;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TRestParticleSource;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TRestParticleCollection;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_vectorlETRestParticlecOallocatorlETRestParticlegRsPgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_reverse_iteratorlEvectorlETRestParticlecOallocatorlETRestParticlegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_TRestG4PrimaryGenerator;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_vectorlETRestParticleSourcecOallocatorlETRestParticleSourcegRsPgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_reverse_iteratorlEvectorlETRestParticleSourcecOallocatorlETRestParticleSourcegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_vectorlETRestParticleCollectioncOallocatorlETRestParticleCollectiongRsPgR;
extern G__linked_taginfo G__TRestG4PrimaryGeneratorLN_reverse_iteratorlEvectorlETRestParticleCollectioncOallocatorlETRestParticleCollectiongRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
