/********************************************************************
* dict/TRestParticle.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestParticle.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestParticle();
extern void G__cpp_setup_inheritanceTRestParticle();
extern void G__cpp_setup_typetableTRestParticle();
extern void G__cpp_setup_memvarTRestParticle();
extern void G__cpp_setup_globalTRestParticle();
extern void G__cpp_setup_memfuncTRestParticle();
extern void G__cpp_setup_funcTRestParticle();
extern void G__set_cpp_environmentTRestParticle();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestParticle.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestParticleLN_TClass;
extern G__linked_taginfo G__TRestParticleLN_TBuffer;
extern G__linked_taginfo G__TRestParticleLN_TMemberInspector;
extern G__linked_taginfo G__TRestParticleLN_TObject;
extern G__linked_taginfo G__TRestParticleLN_TString;
extern G__linked_taginfo G__TRestParticleLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestParticleLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestParticleLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestParticleLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestParticleLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TRestParticleLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TRestParticleLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TRestParticleLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TRestParticleLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TRestParticleLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TRestParticleLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TRestParticleLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TRestParticleLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TRestParticleLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestParticleLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TRestParticleLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TRestParticleLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TRestParticleLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TRestParticleLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestParticleLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TRestParticleLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TRestParticleLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TRestParticleLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TRestParticleLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TRestParticleLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TRestParticleLN_TVector3;
extern G__linked_taginfo G__TRestParticleLN_TRestParticle;

/* STUB derived class for protected member access */
