include ../../.Makefile.arch
include ../../.Makefile.REST

CLASSES = TRestG4Metadata TRestBiasingVolume TRestG4PrimaryGenerator TRestParticleCollection TRestParticle TRestParticleSource

include ../../.Makefile.Class
