/********************************************************************
* dict/TRestSignal.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestSignal.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestSignal();
extern void G__cpp_setup_inheritanceTRestSignal();
extern void G__cpp_setup_typetableTRestSignal();
extern void G__cpp_setup_memvarTRestSignal();
extern void G__cpp_setup_globalTRestSignal();
extern void G__cpp_setup_memfuncTRestSignal();
extern void G__cpp_setup_funcTRestSignal();
extern void G__set_cpp_environmentTRestSignal();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestSignal.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestSignalLN_TClass;
extern G__linked_taginfo G__TRestSignalLN_TBuffer;
extern G__linked_taginfo G__TRestSignalLN_TMemberInspector;
extern G__linked_taginfo G__TRestSignalLN_TObject;
extern G__linked_taginfo G__TRestSignalLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestSignalLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestSignalLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestSignalLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestSignalLN_TVector2;
extern G__linked_taginfo G__TRestSignalLN_TRestSignal;
extern G__linked_taginfo G__TRestSignalLN_vectorlETVector2cOallocatorlETVector2gRsPgR;
extern G__linked_taginfo G__TRestSignalLN_reverse_iteratorlEvectorlETVector2cOallocatorlETVector2gRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
