/********************************************************************
* dict/TRestHitsEvent.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestHitsEvent.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestHitsEvent();
extern void G__cpp_setup_inheritanceTRestHitsEvent();
extern void G__cpp_setup_typetableTRestHitsEvent();
extern void G__cpp_setup_memvarTRestHitsEvent();
extern void G__cpp_setup_globalTRestHitsEvent();
extern void G__cpp_setup_memfuncTRestHitsEvent();
extern void G__cpp_setup_funcTRestHitsEvent();
extern void G__set_cpp_environmentTRestHitsEvent();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestHitsEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestHitsEventLN_TClass;
extern G__linked_taginfo G__TRestHitsEventLN_TBuffer;
extern G__linked_taginfo G__TRestHitsEventLN_TMemberInspector;
extern G__linked_taginfo G__TRestHitsEventLN_TObject;
extern G__linked_taginfo G__TRestHitsEventLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestHitsEventLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestHitsEventLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestHitsEventLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestHitsEventLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TRestHitsEventLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TRestHitsEventLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TRestHitsEventLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TRestHitsEventLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TRestHitsEventLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TRestHitsEventLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TRestHitsEventLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TRestHitsEventLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TRestHitsEventLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestHitsEventLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TRestHitsEventLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TRestHitsEventLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TRestHitsEventLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TRestHitsEventLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestHitsEventLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TRestHitsEventLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TRestHitsEventLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TRestHitsEventLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TRestHitsEventLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TRestHitsEventLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TRestHitsEventLN_TVector3;
extern G__linked_taginfo G__TRestHitsEventLN_TRestEvent;
extern G__linked_taginfo G__TRestHitsEventLN_TRestHitsEvent;
extern G__linked_taginfo G__TRestHitsEventLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TRestHitsEventLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
