/********************************************************************
* dict/TRestSignalEvent.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestSignalEvent.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestSignalEvent();
extern void G__cpp_setup_inheritanceTRestSignalEvent();
extern void G__cpp_setup_typetableTRestSignalEvent();
extern void G__cpp_setup_memvarTRestSignalEvent();
extern void G__cpp_setup_globalTRestSignalEvent();
extern void G__cpp_setup_memfuncTRestSignalEvent();
extern void G__cpp_setup_funcTRestSignalEvent();
extern void G__set_cpp_environmentTRestSignalEvent();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestSignalEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestSignalEventLN_TClass;
extern G__linked_taginfo G__TRestSignalEventLN_TBuffer;
extern G__linked_taginfo G__TRestSignalEventLN_TMemberInspector;
extern G__linked_taginfo G__TRestSignalEventLN_TObject;
extern G__linked_taginfo G__TRestSignalEventLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestSignalEventLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestSignalEventLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestSignalEventLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestSignalEventLN_TRestEvent;
extern G__linked_taginfo G__TRestSignalEventLN_TRestSignal;
extern G__linked_taginfo G__TRestSignalEventLN_vectorlETVector2cOallocatorlETVector2gRsPgR;
extern G__linked_taginfo G__TRestSignalEventLN_reverse_iteratorlEvectorlETVector2cOallocatorlETVector2gRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestSignalEventLN_TRestSignalEvent;
extern G__linked_taginfo G__TRestSignalEventLN_vectorlETRestSignalcOallocatorlETRestSignalgRsPgR;
extern G__linked_taginfo G__TRestSignalEventLN_reverse_iteratorlEvectorlETRestSignalcOallocatorlETRestSignalgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
