/********************************************************************
* dict/TRestElectronDiffusionEvent.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestElectronDiffusionEvent.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestElectronDiffusionEvent();
extern void G__cpp_setup_inheritanceTRestElectronDiffusionEvent();
extern void G__cpp_setup_typetableTRestElectronDiffusionEvent();
extern void G__cpp_setup_memvarTRestElectronDiffusionEvent();
extern void G__cpp_setup_globalTRestElectronDiffusionEvent();
extern void G__cpp_setup_memfuncTRestElectronDiffusionEvent();
extern void G__cpp_setup_funcTRestElectronDiffusionEvent();
extern void G__set_cpp_environmentTRestElectronDiffusionEvent();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestElectronDiffusionEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TClass;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TBuffer;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TMemberInspector;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TObject;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TVector3;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TRestEvent;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_TRestElectronDiffusionEvent;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_vectorlETVector3cOallocatorlETVector3gRsPgR;
extern G__linked_taginfo G__TRestElectronDiffusionEventLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
