/********************************************************************
* dict/TRestHits.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestHits.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestHits();
extern void G__cpp_setup_inheritanceTRestHits();
extern void G__cpp_setup_typetableTRestHits();
extern void G__cpp_setup_memvarTRestHits();
extern void G__cpp_setup_globalTRestHits();
extern void G__cpp_setup_memfuncTRestHits();
extern void G__cpp_setup_funcTRestHits();
extern void G__set_cpp_environmentTRestHits();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestHits.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestHitsLN_TClass;
extern G__linked_taginfo G__TRestHitsLN_TBuffer;
extern G__linked_taginfo G__TRestHitsLN_TMemberInspector;
extern G__linked_taginfo G__TRestHitsLN_TObject;
extern G__linked_taginfo G__TRestHitsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestHitsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestHitsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestHitsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestHitsLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TRestHitsLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TRestHitsLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TRestHitsLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TRestHitsLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TRestHitsLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TRestHitsLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TRestHitsLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TRestHitsLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TRestHitsLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestHitsLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TRestHitsLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TRestHitsLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TRestHitsLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TRestHitsLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestHitsLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TRestHitsLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TRestHitsLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TRestHitsLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TRestHitsLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TRestHitsLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TRestHitsLN_TVector3;
extern G__linked_taginfo G__TRestHitsLN_TRestHits;
extern G__linked_taginfo G__TRestHitsLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TRestHitsLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
