/********************************************************************
* dict/TRestG4Event.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestG4Event.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestG4Event();
extern void G__cpp_setup_inheritanceTRestG4Event();
extern void G__cpp_setup_typetableTRestG4Event();
extern void G__cpp_setup_memvarTRestG4Event();
extern void G__cpp_setup_globalTRestG4Event();
extern void G__cpp_setup_memfuncTRestG4Event();
extern void G__cpp_setup_funcTRestG4Event();
extern void G__set_cpp_environmentTRestG4Event();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestG4Event.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestG4EventLN_TClass;
extern G__linked_taginfo G__TRestG4EventLN_TBuffer;
extern G__linked_taginfo G__TRestG4EventLN_TMemberInspector;
extern G__linked_taginfo G__TRestG4EventLN_TObject;
extern G__linked_taginfo G__TRestG4EventLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TRestG4EventLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestG4EventLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestG4EventLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestG4EventLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestG4EventLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TRestG4EventLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TRestG4EventLN_TRestEvent;
extern G__linked_taginfo G__TRestG4EventLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TRestG4EventLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TRestG4EventLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TRestG4EventLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TRestG4EventLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TRestG4EventLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TRestG4EventLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TRestG4EventLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestG4EventLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TRestG4EventLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TRestG4EventLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TRestG4EventLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TRestG4EventLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestG4EventLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TRestG4EventLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TRestG4EventLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TRestG4EventLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TRestG4EventLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TRestG4EventLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TRestG4EventLN_TVector3;
extern G__linked_taginfo G__TRestG4EventLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TRestG4EventLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestG4EventLN_TRestG4Track;
extern G__linked_taginfo G__TRestG4EventLN_TRestG4Event;
extern G__linked_taginfo G__TRestG4EventLN_vectorlETVector3cOallocatorlETVector3gRsPgR;
extern G__linked_taginfo G__TRestG4EventLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestG4EventLN_vectorlETRestG4TrackcOallocatorlETRestG4TrackgRsPgR;
extern G__linked_taginfo G__TRestG4EventLN_reverse_iteratorlEvectorlETRestG4TrackcOallocatorlETRestG4TrackgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
