/********************************************************************
* dict/TRestG4Track.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestG4Track.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestG4Track();
extern void G__cpp_setup_inheritanceTRestG4Track();
extern void G__cpp_setup_typetableTRestG4Track();
extern void G__cpp_setup_memvarTRestG4Track();
extern void G__cpp_setup_globalTRestG4Track();
extern void G__cpp_setup_memfuncTRestG4Track();
extern void G__cpp_setup_funcTRestG4Track();
extern void G__set_cpp_environmentTRestG4Track();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestG4Track.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestG4TrackLN_TClass;
extern G__linked_taginfo G__TRestG4TrackLN_TBuffer;
extern G__linked_taginfo G__TRestG4TrackLN_TMemberInspector;
extern G__linked_taginfo G__TRestG4TrackLN_TObject;
extern G__linked_taginfo G__TRestG4TrackLN_TString;
extern G__linked_taginfo G__TRestG4TrackLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestG4TrackLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestG4TrackLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestG4TrackLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestG4TrackLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TRestG4TrackLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TRestG4TrackLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TRestG4TrackLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TRestG4TrackLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TRestG4TrackLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TRestG4TrackLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TRestG4TrackLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TRestG4TrackLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TRestG4TrackLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestG4TrackLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TRestG4TrackLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TRestG4TrackLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TRestG4TrackLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TRestG4TrackLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestG4TrackLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TRestG4TrackLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TRestG4TrackLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TRestG4TrackLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TRestG4TrackLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TRestG4TrackLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TRestG4TrackLN_TVector3;
extern G__linked_taginfo G__TRestG4TrackLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TRestG4TrackLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestG4TrackLN_TRestG4Hits;
extern G__linked_taginfo G__TRestG4TrackLN_TRestG4Track;

/* STUB derived class for protected member access */
