/********************************************************************
* dict/TRestG4Hits.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TRestG4Hits.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRestG4Hits();
extern void G__cpp_setup_inheritanceTRestG4Hits();
extern void G__cpp_setup_typetableTRestG4Hits();
extern void G__cpp_setup_memvarTRestG4Hits();
extern void G__cpp_setup_globalTRestG4Hits();
extern void G__cpp_setup_memfuncTRestG4Hits();
extern void G__cpp_setup_funcTRestG4Hits();
extern void G__set_cpp_environmentTRestG4Hits();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TRestG4Hits.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRestG4HitsLN_TClass;
extern G__linked_taginfo G__TRestG4HitsLN_TBuffer;
extern G__linked_taginfo G__TRestG4HitsLN_TMemberInspector;
extern G__linked_taginfo G__TRestG4HitsLN_TObject;
extern G__linked_taginfo G__TRestG4HitsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRestG4HitsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestG4HitsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRestG4HitsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestG4HitsLN_TArrayI;
extern G__linked_taginfo G__TRestG4HitsLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TRestG4HitsLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TRestG4HitsLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TRestG4HitsLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TRestG4HitsLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TRestG4HitsLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TRestG4HitsLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TRestG4HitsLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TRestG4HitsLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TRestG4HitsLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestG4HitsLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TRestG4HitsLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TRestG4HitsLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TRestG4HitsLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TRestG4HitsLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TRestG4HitsLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TRestG4HitsLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TRestG4HitsLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TRestG4HitsLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TRestG4HitsLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TRestG4HitsLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TRestG4HitsLN_TVector3;
extern G__linked_taginfo G__TRestG4HitsLN_TRestHits;
extern G__linked_taginfo G__TRestG4HitsLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TRestG4HitsLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRestG4HitsLN_TRestG4Hits;

/* STUB derived class for protected member access */
