
REST_FW = $(REST_PATH)/source
PATH_LIB = $(REST_PATH)/lib/

# Compiler to be used
CC = g++-4.9

#Flags
FLAGS = -fPIC -Wall -g -std=c++0x -Wabi-tag

REST_MAIN_INC = -I$(REST_FW)/restcore/inc -I$(REST_FW)/tools/inc
REST_PROCESS_INC = -I$(REST_FW)/processes/signal/inc -I$(REST_FW)/processes/raw/inc -I$(REST_FW)/processes/analysis/inc -I$(REST_FW)/processes/general/inc
REST_EVENTS_INC = -I$(REST_FW)/events/geant4/inc -I$(REST_FW)/events/general/inc -I$(REST_FW)/events/analysis/inc
REST_VIEWERS_INC = -I$(REST_FW)/viewers/general/inc -I$(REST_FW)/viewers/geant4/inc
REST_METADATA_INC = -I$(REST_FW)/metadata/general/inc -I$(REST_FW)/metadata/geant4/inc -I$(REST_FW)/metadata/readout/inc
REST_EXTERNAL_INC = -I$(REST_FW)/external/tsp/inc

REST_INC = $(REST_MAIN_INC) $(REST_PROCESS_INC) $(REST_EVENTS_INC) $(REST_VIEWERS_INC) $(REST_METADATA_INC) $(REST_EXTERNAL_INC)

# "include" directories in which to search for .h files
INC_DIRS = -I. -I./inc $(REST_INC) -I$(shell $(ROOTCONFIG) --incdir) -I$(GARFIELD_HOME)/Include

# Libraries
ROOTLIBS := $(shell root-config --libs)
LIBS = -lm ${ROOTLIBS} -lEve -lGeom -L$(PATH_LIB) -L/usr/lib -L$(GARFIELD_HOME)/lib -lGarfield
